# Generated by Django 3.2.5 on 2022-09-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20220803_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
